1. IMPORT

In [1]:
import pandas as pd
import numpy as np

2. DATA LOADING

In [2]:
data = pd.read_csv('Pokemon.csv')

3. DATA CLEANING

In [3]:
data

       #                   Name   Type 1  ... Speed  Generation  Legendary
0      1              Bulbasaur    Grass  ...    45           1      False
1      2                Ivysaur    Grass  ...    60           1      False
2      3               Venusaur    Grass  ...    80           1      False
3      3  VenusaurMega Venusaur    Grass  ...    80           1      False
4      4             Charmander     Fire  ...    65           1      False
..   ...                    ...      ...  ...   ...         ...        ...
795  719                Diancie     Rock  ...    50           6       True
796  719    DiancieMega Diancie     Rock  ...   110           6       True
797  720    HoopaHoopa Confined  Psychic  ...    70           6       True
798  720     HoopaHoopa Unbound  Psychic  ...    80           6       True
799  721              Volcanion     Fire  ...    70           6       True

[800 rows x 13 columns]

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

There is 386 null object in type 2

In [7]:
data.describe().transpose()

            count       mean         std    min     25%    50%     75%    max
#           800.0  362.81375  208.343798    1.0  184.75  364.5  539.25  721.0
Total       800.0  435.10250  119.963040  180.0  330.00  450.0  515.00  780.0
HP          800.0   69.25875   25.534669    1.0   50.00   65.0   80.00  255.0
Attack      800.0   79.00125   32.457366    5.0   55.00   75.0  100.00  190.0
Defense     800.0   73.84250   31.183501    5.0   50.00   70.0   90.00  230.0
Sp. Atk     800.0   72.82000   32.722294   10.0   49.75   65.0   95.00  194.0
Sp. Def     800.0   71.90250   27.828916   20.0   50.00   70.0   90.00  230.0
Speed       800.0   68.27750   29.060474    5.0   45.00   65.0   90.00  180.0
Generation  800.0    3.32375    1.661290    1.0    2.00    3.0    5.00    6.0

A weird things about this is There is 1 HP

Upon inspecting, there is a Pokemon which have 1 HP, the Shedinja

In [9]:
data[data['HP']==1]

       #      Name Type 1 Type 2  ...  Sp. Def  Speed  Generation  Legendary
316  292  Shedinja    Bug  Ghost  ...       30     40           3      False

[1 rows x 13 columns]

Fill None For Type

In [10]:
data['Type 2'] = data['Type 2'].fillna('None')

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      800 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

Check Unique Name

In [12]:
data.Name.unique()

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 'VenusaurMega Venusaur',
       'Charmander', 'Charmeleon', 'Charizard',
       'CharizardMega Charizard X', 'CharizardMega Charizard Y',
       'Squirtle', 'Wartortle', 'Blastoise', 'BlastoiseMega Blastoise',
       'Caterpie', 'Metapod', 'Butterfree', 'Weedle', 'Kakuna',
       'Beedrill', 'BeedrillMega Beedrill', 'Pidgey', 'Pidgeotto',
       'Pidgeot', 'PidgeotMega Pidgeot', 'Rattata', 'Raticate', 'Spearow',
       'Fearow', 'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew',
       'Sandslash', 'Nidoranâ™€', 'Nidorina', 'Nidoqueen', 'Nidoranâ™‚',
       'Nidorino', 'Nidoking', 'Clefairy', 'Clefable', 'Vulpix',
       'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat',
       'Oddish', 'Gloom', 'Vileplume', 'Paras', 'Parasect', 'Venonat',
       'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian', 'Psyduck',
       'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine',
       'Poliwag', 'Poliwhirl', 'Poliwrath', 'Abra', 'Kadabra', 'Alakazam',
       'AlakazamMega Alakazam', 'Machop', 'Machoke', 'Machamp',
       'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool',
       'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash',
       'Slowpoke', 'Slowbro', 'SlowbroMega Slowbro', 'Magnemite',
       'Magneton', "Farfetch'd", 'Doduo', 'Dodrio', 'Seel', 'Dewgong',
       'Grimer', 'Muk', 'Shellder', 'Cloyster', 'Gastly', 'Haunter',
       'Gengar', 'GengarMega Gengar', 'Onix', 'Drowzee', 'Hypno',
       'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute',
       'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan',
       'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey',
       'Tangela', 'Kangaskhan', 'KangaskhanMega Kangaskhan', 'Horsea',
       'Seadra', 'Goldeen', 'Seaking', 'Staryu', 'Starmie', 'Mr. Mime',
       'Scyther', 'Jynx', 'Electabuzz', 'Magmar', 'Pinsir',
       'PinsirMega Pinsir', 'Tauros', 'Magikarp', 'Gyarados',
       'GyaradosMega Gyarados', 'Lapras', 'Ditto', 'Eevee', 'Vaporeon',
       'Jolteon', 'Flareon', 'Porygon', 'Omanyte', 'Omastar', 'Kabuto',
       'Kabutops', 'Aerodactyl', 'AerodactylMega Aerodactyl', 'Snorlax',
       'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair',
       'Dragonite', 'Mewtwo', 'MewtwoMega Mewtwo X',
       'MewtwoMega Mewtwo Y', 'Mew', 'Chikorita', 'Bayleef', 'Meganium',
       'Cyndaquil', 'Quilava', 'Typhlosion', 'Totodile', 'Croconaw',
       'Feraligatr', 'Sentret', 'Furret', 'Hoothoot', 'Noctowl', 'Ledyba',
       'Ledian', 'Spinarak', 'Ariados', 'Crobat', 'Chinchou', 'Lanturn',
       'Pichu', 'Cleffa', 'Igglybuff', 'Togepi', 'Togetic', 'Natu',
       'Xatu', 'Mareep', 'Flaaffy', 'Ampharos', 'AmpharosMega Ampharos',
       'Bellossom', 'Marill', 'Azumarill', 'Sudowoodo', 'Politoed',
       'Hoppip', 'Skiploom', 'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora',
       'Yanma', 'Wooper', 'Quagsire', 'Espeon', 'Umbreon', 'Murkrow',
       'Slowking', 'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig',
       'Pineco', 'Forretress', 'Dunsparce', 'Gligar', 'Steelix',
       'SteelixMega Steelix', 'Snubbull', 'Granbull', 'Qwilfish',
       'Scizor', 'ScizorMega Scizor', 'Shuckle', 'Heracross',
       'HeracrossMega Heracross', 'Sneasel', 'Teddiursa', 'Ursaring',
       'Slugma', 'Magcargo', 'Swinub', 'Piloswine', 'Corsola', 'Remoraid',
       'Octillery', 'Delibird', 'Mantine', 'Skarmory', 'Houndour',
       'Houndoom', 'HoundoomMega Houndoom', 'Kingdra', 'Phanpy',
       'Donphan', 'Porygon2', 'Stantler', 'Smeargle', 'Tyrogue',
       'Hitmontop', 'Smoochum', 'Elekid', 'Magby', 'Miltank', 'Blissey',
       'Raikou', 'Entei', 'Suicune', 'Larvitar', 'Pupitar', 'Tyranitar',
       'TyranitarMega Tyranitar', 'Lugia', 'Ho-oh', 'Celebi', 'Treecko',
       'Grovyle', 'Sceptile', 'SceptileMega Sceptile', 'Torchic',
       'Combusken', 'Blaziken', 'BlazikenMega Blaziken', 'Mudkip',
       'Marshtomp', 'Swampert', 'SwampertMega Swampert', 'Poochyena',
       'Mightyena', 'Zigzagoon', 'Linoone', 'Wurmple', 'Silcoon',
       'Beautifly', 'Cascoon', 'Dustox', 'Lotad', 'Lombre', 'Ludicolo',
       'Seedot', 'Nuzleaf', 'Shiftry', 'Taillow', 'Swellow', 'Wingull',
       'Pelipper', 'Ralts', 'Kirlia', 'Gardevoir',
       'GardevoirMega Gardevoir', 'Surskit', 'Masquerain', 'Shroomish',
       'Breloom', 'Slakoth', 'Vigoroth', 'Slaking', 'Nincada', 'Ninjask',
       'Shedinja', 'Whismur', 'Loudred', 'Exploud', 'Makuhita',
       'Hariyama', 'Azurill', 'Nosepass', 'Skitty', 'Delcatty', 'Sableye',
       'SableyeMega Sableye', 'Mawile', 'MawileMega Mawile', 'Aron',
       'Lairon', 'Aggron', 'AggronMega Aggron', 'Meditite', 'Medicham',
       'MedichamMega Medicham', 'Electrike', 'Manectric',
       'ManectricMega Manectric', 'Plusle', 'Minun', 'Volbeat',
       'Illumise', 'Roselia', 'Gulpin', 'Swalot', 'Carvanha', 'Sharpedo',
       'SharpedoMega Sharpedo', 'Wailmer', 'Wailord', 'Numel', 'Camerupt',
       'CameruptMega Camerupt', 'Torkoal', 'Spoink', 'Grumpig', 'Spinda',
       'Trapinch', 'Vibrava', 'Flygon', 'Cacnea', 'Cacturne', 'Swablu',
       'Altaria', 'AltariaMega Altaria', 'Zangoose', 'Seviper',
       'Lunatone', 'Solrock', 'Barboach', 'Whiscash', 'Corphish',
       'Crawdaunt', 'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith',
       'Armaldo', 'Feebas', 'Milotic', 'Castform', 'Kecleon', 'Shuppet',
       'Banette', 'BanetteMega Banette', 'Duskull', 'Dusclops', 'Tropius',
       'Chimecho', 'Absol', 'AbsolMega Absol', 'Wynaut', 'Snorunt',
       'Glalie', 'GlalieMega Glalie', 'Spheal', 'Sealeo', 'Walrein',
       'Clamperl', 'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon',
       'Shelgon', 'Salamence', 'SalamenceMega Salamence', 'Beldum',
       'Metang', 'Metagross', 'MetagrossMega Metagross', 'Regirock',
       'Regice', 'Registeel', 'Latias', 'LatiasMega Latias', 'Latios',
       'LatiosMega Latios', 'Kyogre', 'KyogrePrimal Kyogre', 'Groudon',
       'GroudonPrimal Groudon', 'Rayquaza', 'RayquazaMega Rayquaza',
       'Jirachi', 'DeoxysNormal Forme', 'DeoxysAttack Forme',
       'DeoxysDefense Forme', 'DeoxysSpeed Forme', 'Turtwig', 'Grotle',
       'Torterra', 'Chimchar', 'Monferno', 'Infernape', 'Piplup',
       'Prinplup', 'Empoleon', 'Starly', 'Staravia', 'Staraptor',
       'Bidoof', 'Bibarel', 'Kricketot', 'Kricketune', 'Shinx', 'Luxio',
       'Luxray', 'Budew', 'Roserade', 'Cranidos', 'Rampardos', 'Shieldon',
       'Bastiodon', 'Burmy', 'WormadamPlant Cloak', 'WormadamSandy Cloak',
       'WormadamTrash Cloak', 'Mothim', 'Combee', 'Vespiquen',
       'Pachirisu', 'Buizel', 'Floatzel', 'Cherubi', 'Cherrim', 'Shellos',
       'Gastrodon', 'Ambipom', 'Drifloon', 'Drifblim', 'Buneary',
       'Lopunny', 'LopunnyMega Lopunny', 'Mismagius', 'Honchkrow',
       'Glameow', 'Purugly', 'Chingling', 'Stunky', 'Skuntank', 'Bronzor',
       'Bronzong', 'Bonsly', 'Mime Jr.', 'Happiny', 'Chatot', 'Spiritomb',
       'Gible', 'Gabite', 'Garchomp', 'GarchompMega Garchomp', 'Munchlax',
       'Riolu', 'Lucario', 'LucarioMega Lucario', 'Hippopotas',
       'Hippowdon', 'Skorupi', 'Drapion', 'Croagunk', 'Toxicroak',
       'Carnivine', 'Finneon', 'Lumineon', 'Mantyke', 'Snover',
       'Abomasnow', 'AbomasnowMega Abomasnow', 'Weavile', 'Magnezone',
       'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire', 'Magmortar',
       'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor',
       'Mamoswine', 'Porygon-Z', 'Gallade', 'GalladeMega Gallade',
       'Probopass', 'Dusknoir', 'Froslass', 'Rotom', 'RotomHeat Rotom',
       'RotomWash Rotom', 'RotomFrost Rotom', 'RotomFan Rotom',
       'RotomMow Rotom', 'Uxie', 'Mesprit', 'Azelf', 'Dialga', 'Palkia',
       'Heatran', 'Regigigas', 'GiratinaAltered Forme',
       'GiratinaOrigin Forme', 'Cresselia', 'Phione', 'Manaphy',
       'Darkrai', 'ShayminLand Forme', 'ShayminSky Forme', 'Arceus',
       'Victini', 'Snivy', 'Servine', 'Serperior', 'Tepig', 'Pignite',
       'Emboar', 'Oshawott', 'Dewott', 'Samurott', 'Patrat', 'Watchog',
       'Lillipup', 'Herdier', 'Stoutland', 'Purrloin', 'Liepard',
       'Pansage', 'Simisage', 'Pansear', 'Simisear', 'Panpour',
       'Simipour', 'Munna', 'Musharna', 'Pidove', 'Tranquill', 'Unfezant',
       'Blitzle', 'Zebstrika', 'Roggenrola', 'Boldore', 'Gigalith',
       'Woobat', 'Swoobat', 'Drilbur', 'Excadrill', 'Audino',
       'AudinoMega Audino', 'Timburr', 'Gurdurr', 'Conkeldurr', 'Tympole',
       'Palpitoad', 'Seismitoad', 'Throh', 'Sawk', 'Sewaddle', 'Swadloon',
       'Leavanny', 'Venipede', 'Whirlipede', 'Scolipede', 'Cottonee',
       'Whimsicott', 'Petilil', 'Lilligant', 'Basculin', 'Sandile',
       'Krokorok', 'Krookodile', 'Darumaka', 'DarmanitanStandard Mode',
       'DarmanitanZen Mode', 'Maractus', 'Dwebble', 'Crustle', 'Scraggy',
       'Scrafty', 'Sigilyph', 'Yamask', 'Cofagrigus', 'Tirtouga',
       'Carracosta', 'Archen', 'Archeops', 'Trubbish', 'Garbodor',
       'Zorua', 'Zoroark', 'Minccino', 'Cinccino', 'Gothita', 'Gothorita',
       'Gothitelle', 'Solosis', 'Duosion', 'Reuniclus', 'Ducklett',
       'Swanna', 'Vanillite', 'Vanillish', 'Vanilluxe', 'Deerling',
       'Sawsbuck', 'Emolga', 'Karrablast', 'Escavalier', 'Foongus',
       'Amoonguss', 'Frillish', 'Jellicent', 'Alomomola', 'Joltik',
       'Galvantula', 'Ferroseed', 'Ferrothorn', 'Klink', 'Klang',
       'Klinklang', 'Tynamo', 'Eelektrik', 'Eelektross', 'Elgyem',
       'Beheeyem', 'Litwick', 'Lampent', 'Chandelure', 'Axew', 'Fraxure',
       'Haxorus', 'Cubchoo', 'Beartic', 'Cryogonal', 'Shelmet',
       'Accelgor', 'Stunfisk', 'Mienfoo', 'Mienshao', 'Druddigon',
       'Golett', 'Golurk', 'Pawniard', 'Bisharp', 'Bouffalant', 'Rufflet',
       'Braviary', 'Vullaby', 'Mandibuzz', 'Heatmor', 'Durant', 'Deino',
       'Zweilous', 'Hydreigon', 'Larvesta', 'Volcarona', 'Cobalion',
       'Terrakion', 'Virizion', 'TornadusIncarnate Forme',
       'TornadusTherian Forme', 'ThundurusIncarnate Forme',
       'ThundurusTherian Forme', 'Reshiram', 'Zekrom',
       'LandorusIncarnate Forme', 'LandorusTherian Forme', 'Kyurem',
       'KyuremBlack Kyurem', 'KyuremWhite Kyurem', 'KeldeoOrdinary Forme',
       'KeldeoResolute Forme', 'MeloettaAria Forme',
       'MeloettaPirouette Forme', 'Genesect', 'Chespin', 'Quilladin',
       'Chesnaught', 'Fennekin', 'Braixen', 'Delphox', 'Froakie',
       'Frogadier', 'Greninja', 'Bunnelby', 'Diggersby', 'Fletchling',
       'Fletchinder', 'Talonflame', 'Scatterbug', 'Spewpa', 'Vivillon',
       'Litleo', 'Pyroar', 'FlabÃ©bÃ©', 'Floette', 'Florges', 'Skiddo',
       'Gogoat', 'Pancham', 'Pangoro', 'Furfrou', 'Espurr',
       'MeowsticMale', 'MeowsticFemale', 'Honedge', 'Doublade',
       'AegislashBlade Forme', 'AegislashShield Forme', 'Spritzee',
       'Aromatisse', 'Swirlix', 'Slurpuff', 'Inkay', 'Malamar', 'Binacle',
       'Barbaracle', 'Skrelp', 'Dragalge', 'Clauncher', 'Clawitzer',
       'Helioptile', 'Heliolisk', 'Tyrunt', 'Tyrantrum', 'Amaura',
       'Aurorus', 'Sylveon', 'Hawlucha', 'Dedenne', 'Carbink', 'Goomy',
       'Sliggoo', 'Goodra', 'Klefki', 'Phantump', 'Trevenant',
       'PumpkabooAverage Size', 'PumpkabooSmall Size',
       'PumpkabooLarge Size', 'PumpkabooSuper Size',
       'GourgeistAverage Size', 'GourgeistSmall Size',
       'GourgeistLarge Size', 'GourgeistSuper Size', 'Bergmite',
       'Avalugg', 'Noibat', 'Noivern', 'Xerneas', 'Yveltal',
       'Zygarde50% Forme', 'Diancie', 'DiancieMega Diancie',
       'HoopaHoopa Confined', 'HoopaHoopa Unbound', 'Volcanion'],
      dtype=object)

It seems that there is a lot of variation per Name

In [2]:
data.set_index('#', inplace=True)

In [18]:
data.iloc[710]

Name          Kyurem
Type 1        Dragon
Type 2           Ice
Total            660
HP               125
Attack           130
Defense           90
Sp. Atk          130
Sp. Def           90
Speed             95
Generation         5
Legendary       True
Name: 646, dtype: object